### ISSUE TITLE
TODOs

### ISSUE THREAD

**Issue by 488Ques** [488Ques/gomsuviet#1]
### TODO:
- [ ] Sửa lại danh mục sản phẩm
- [ ] Sửa lại tag
- [ ] Sửa lại carousel của home page
- [ ] Làm thanh toán bằng ví MOMO hoặc sử dụng các API thanh toán khác (Low = Ưu tiên thấp)
- [ ] Làm đánh giá sản phẩm của người mua (Low)
- [ ] Làm lại phần lọc sản phẩm theo tag (Low)
---
- [ ] Làm phần đăng ký tài khoản của người bán
- [ ] Làm phần đăng tin bán hàng
- [ ] Làm phần quản lý đơn hàng
- [ ] Làm phần thống kê doanh số
